VueComponent {
  _uid: 4,
  _isVue: true,
  '$options':
   { parent:
      VueComponent {
        _uid: 3,
        _isVue: true,
        '$options': [Object],
        _renderProxy: [VueComponent],
        _self: [Circular],
        '$parent': undefined,
        '$root': [Circular],
        '$children': [Array],
        '$refs': [Object],
        _watcher: [Watcher],
        _inactive: null,
        _directInactive: false,
        _isMounted: true,
        _isDestroyed: false,
        _isBeingDestroyed: false,
        _events: {},
        _hasHookEvent: false,
        _vnode: [VNode],
        _staticTrees: null,
        '$vnode': undefined,
        '$slots': {},
        '$scopedSlots': {},
        _c: [Function],
        '$createElement': [Function],
        '$attrs': [Getter/Setter],
        '$listeners': [Getter/Setter],
        __emitted: {},
        __emittedByOrder: [],
        '$emit': [Function],
        _watchers: [Array],
        _data: {},
        _provided: undefined,
        '$el': [HTMLDivElement] },
     _parentVnode:
      VNode {
        tag: 'vue-component-8-Test',
        data: [Object],
        children: undefined,
        text: undefined,
        elm: [HTMLDivElement],
        ns: undefined,
        context: [VueComponent],
        fnContext: undefined,
        fnOptions: undefined,
        fnScopeId: undefined,
        key: undefined,
        componentOptions: [Object],
        componentInstance: [Circular],
        parent: undefined,
        raw: false,
        isStatic: false,
        isRootInsert: true,
        isComment: false,
        isCloned: false,
        isOnce: false,
        asyncFactory: undefined,
        asyncMeta: undefined,
        isAsyncPlaceholder: false },
     _parentElm: null,
     _refElm: null,
     propsData: {},
     _parentListeners: undefined,
     _renderChildren: undefined,
     _componentTag: undefined,
     _propKeys: [ 'slug' ] },
  _renderProxy:
   VueComponent {
     _uid: 4,
     _isVue: true,
     '$options':
      { parent: [VueComponent],
        _parentVnode: [VNode],
        _parentElm: null,
        _refElm: null,
        propsData: {},
        _parentListeners: undefined,
        _renderChildren: undefined,
        _componentTag: undefined,
        _propKeys: [Array] },
     _renderProxy: [Circular],
     _self: [Circular],
     '$parent':
      VueComponent {
        _uid: 3,
        _isVue: true,
        '$options': [Object],
        _renderProxy: [VueComponent],
        _self: [Circular],
        '$parent': undefined,
        '$root': [Circular],
        '$children': [Array],
        '$refs': [Object],
        _watcher: [Watcher],
        _inactive: null,
        _directInactive: false,
        _isMounted: true,
        _isDestroyed: false,
        _isBeingDestroyed: false,
        _events: {},
        _hasHookEvent: false,
        _vnode: [VNode],
        _staticTrees: null,
        '$vnode': undefined,
        '$slots': {},
        '$scopedSlots': {},
        _c: [Function],
        '$createElement': [Function],
        '$attrs': [Getter/Setter],
        '$listeners': [Getter/Setter],
        __emitted: {},
        __emittedByOrder: [],
        '$emit': [Function],
        _watchers: [Array],
        _data: {},
        _provided: undefined,
        '$el': [HTMLDivElement] },
     '$root':
      VueComponent {
        _uid: 3,
        _isVue: true,
        '$options': [Object],
        _renderProxy: [VueComponent],
        _self: [Circular],
        '$parent': undefined,
        '$root': [Circular],
        '$children': [Array],
        '$refs': [Object],
        _watcher: [Watcher],
        _inactive: null,
        _directInactive: false,
        _isMounted: true,
        _isDestroyed: false,
        _isBeingDestroyed: false,
        _events: {},
        _hasHookEvent: false,
        _vnode: [VNode],
        _staticTrees: null,
        '$vnode': undefined,
        '$slots': {},
        '$scopedSlots': {},
        _c: [Function],
        '$createElement': [Function],
        '$attrs': [Getter/Setter],
        '$listeners': [Getter/Setter],
        __emitted: {},
        __emittedByOrder: [],
        '$emit': [Function],
        _watchers: [Array],
        _data: {},
        _provided: undefined,
        '$el': [HTMLDivElement] },
     '$children': [ [VueComponent] ],
     '$refs': {},
     _watcher:
      Watcher {
        vm: [Circular],
        sync: true,
        lazy: false,
        user: false,
        deep: false,
        cb: [Function: noop],
        id: 7,
        active: true,
        dirty: false,
        deps: [Array],
        newDeps: [],
        depIds: [Set],
        newDepIds: Set {},
        expression:
         'function () {\n      vm._update(vm._render(), hydrating);\n    }',
        getter: [Function: updateComponent],
        value: undefined },
     _inactive: null,
     _directInactive: false,
     _isMounted: true,
     _isDestroyed: false,
     _isBeingDestroyed: false,
     _events: {},
     _hasHookEvent: false,
     _vnode:
      VNode {
        tag: 'div',
        data: [Object],
        children: [Array],
        text: undefined,
        elm: [HTMLDivElement],
        ns: undefined,
        context: [Circular],
        fnContext: undefined,
        fnOptions: undefined,
        fnScopeId: undefined,
        key: undefined,
        componentOptions: undefined,
        componentInstance: undefined,
        parent: [VNode],
        raw: false,
        isStatic: false,
        isRootInsert: true,
        isComment: false,
        isCloned: false,
        isOnce: false,
        asyncFactory: undefined,
        asyncMeta: undefined,
        isAsyncPlaceholder: false },
     _staticTrees: [ [VNode] ],
     '$vnode':
      VNode {
        tag: 'vue-component-8-Test',
        data: [Object],
        children: undefined,
        text: undefined,
        elm: [HTMLDivElement],
        ns: undefined,
        context: [VueComponent],
        fnContext: undefined,
        fnOptions: undefined,
        fnScopeId: undefined,
        key: undefined,
        componentOptions: [Object],
        componentInstance: [Circular],
        parent: undefined,
        raw: false,
        isStatic: false,
        isRootInsert: true,
        isComment: false,
        isCloned: false,
        isOnce: false,
        asyncFactory: undefined,
        asyncMeta: undefined,
        isAsyncPlaceholder: false },
     '$slots': {},
     '$scopedSlots': {},
     _c: [Function],
     '$createElement': [Function],
     '$attrs': [Getter/Setter],
     '$listeners': [Getter/Setter],
     __emitted: {},
     __emittedByOrder: [],
     '$emit': [Function],
     _watchers: [ [Watcher], [Watcher] ],
     _props: { slug: [Getter/Setter] },
     fetchResults: [Function: bound fetchResults],
     updateCount: [Function: bound updateCount],
     increment: [Function: bound increment],
     decrement: [Function: bound decrement],
     clear: [Function: bound clear],
     onKeydown: [Function: bound onKeydown],
     _data:
      { count: [Getter/Setter],
        quantity: [Getter/Setter],
        value: [Getter/Setter] },
     value: [Getter/Setter],
     quantity: [Getter/Setter],
     count: [Getter/Setter],
     '$el':
      HTMLDivElement {
        _prevClass: 'container py-5 bg-success',
        __vue__: [VueComponent] },
     '$_vueTestUtils_updateInSetWatcherSync': [Function],
     _update: [Function] },
  _self: [Circular],
  '$parent':
   VueComponent {
     _uid: 3,
     _isVue: true,
     '$options':
      { components: [Object],
        directives: {},
        filters: {},
        _base: [Function],
        _Ctor: [Object],
        beforeCreate: [Array],
        beforeMount: [Array],
        provide: [Function: mergedInstanceDataFn],
        render: [Function],
        _refElm: null,
        _parentElm: null },
     _renderProxy:
      VueComponent {
        _uid: 3,
        _isVue: true,
        '$options': [Object],
        _renderProxy: [Circular],
        _self: [Circular],
        '$parent': undefined,
        '$root': [Circular],
        '$children': [Array],
        '$refs': [Object],
        _watcher: [Watcher],
        _inactive: null,
        _directInactive: false,
        _isMounted: true,
        _isDestroyed: false,
        _isBeingDestroyed: false,
        _events: {},
        _hasHookEvent: false,
        _vnode: [VNode],
        _staticTrees: null,
        '$vnode': undefined,
        '$slots': {},
        '$scopedSlots': {},
        _c: [Function],
        '$createElement': [Function],
        '$attrs': [Getter/Setter],
        '$listeners': [Getter/Setter],
        __emitted: {},
        __emittedByOrder: [],
        '$emit': [Function],
        _watchers: [Array],
        _data: {},
        _provided: undefined,
        '$el': [HTMLDivElement] },
     _self: [Circular],
     '$parent': undefined,
     '$root': [Circular],
     '$children': [ [Circular] ],
     '$refs': { vm: [Circular] },
     _watcher:
      Watcher {
        vm: [Circular],
        sync: false,
        lazy: false,
        user: false,
        deep: false,
        cb: [Function: noop],
        id: 5,
        active: true,
        dirty: false,
        deps: [],
        newDeps: [],
        depIds: Set {},
        newDepIds: Set {},
        expression:
         'function () {\n      vm._update(vm._render(), hydrating);\n    }',
        getter: [Function: updateComponent],
        value: undefined },
     _inactive: null,
     _directInactive: false,
     _isMounted: true,
     _isDestroyed: false,
     _isBeingDestroyed: false,
     _events: {},
     _hasHookEvent: false,
     _vnode:
      VNode {
        tag: 'vue-component-8-Test',
        data: [Object],
        children: undefined,
        text: undefined,
        elm: [HTMLDivElement],
        ns: undefined,
        context: [Circular],
        fnContext: undefined,
        fnOptions: undefined,
        fnScopeId: undefined,
        key: undefined,
        componentOptions: [Object],
        componentInstance: [Circular],
        parent: undefined,
        raw: false,
        isStatic: false,
        isRootInsert: true,
        isComment: false,
        isCloned: false,
        isOnce: false,
        asyncFactory: undefined,
        asyncMeta: undefined,
        isAsyncPlaceholder: false },
     _staticTrees: null,
     '$vnode': undefined,
     '$slots': {},
     '$scopedSlots': {},
     _c: [Function],
     '$createElement': [Function],
     '$attrs': [Getter/Setter],
     '$listeners': [Getter/Setter],
     __emitted: {},
     __emittedByOrder: [],
     '$emit': [Function],
     _watchers: [ [Watcher] ],
     _data: {},
     _provided: undefined,
     '$el':
      HTMLDivElement { _prevClass: 'container py-5 bg-success', __vue__: [Circular] } },
  '$root':
   VueComponent {
     _uid: 3,
     _isVue: true,
     '$options':
      { components: [Object],
        directives: {},
        filters: {},
        _base: [Function],
        _Ctor: [Object],
        beforeCreate: [Array],
        beforeMount: [Array],
        provide: [Function: mergedInstanceDataFn],
        render: [Function],
        _refElm: null,
        _parentElm: null },
     _renderProxy:
      VueComponent {
        _uid: 3,
        _isVue: true,
        '$options': [Object],
        _renderProxy: [Circular],
        _self: [Circular],
        '$parent': undefined,
        '$root': [Circular],
        '$children': [Array],
        '$refs': [Object],
        _watcher: [Watcher],
        _inactive: null,
        _directInactive: false,
        _isMounted: true,
        _isDestroyed: false,
        _isBeingDestroyed: false,
        _events: {},
        _hasHookEvent: false,
        _vnode: [VNode],
        _staticTrees: null,
        '$vnode': undefined,
        '$slots': {},
        '$scopedSlots': {},
        _c: [Function],
        '$createElement': [Function],
        '$attrs': [Getter/Setter],
        '$listeners': [Getter/Setter],
        __emitted: {},
        __emittedByOrder: [],
        '$emit': [Function],
        _watchers: [Array],
        _data: {},
        _provided: undefined,
        '$el': [HTMLDivElement] },
     _self: [Circular],
     '$parent': undefined,
     '$root': [Circular],
     '$children': [ [Circular] ],
     '$refs': { vm: [Circular] },
     _watcher:
      Watcher {
        vm: [Circular],
        sync: false,
        lazy: false,
        user: false,
        deep: false,
        cb: [Function: noop],
        id: 5,
        active: true,
        dirty: false,
        deps: [],
        newDeps: [],
        depIds: Set {},
        newDepIds: Set {},
        expression:
         'function () {\n      vm._update(vm._render(), hydrating);\n    }',
        getter: [Function: updateComponent],
        value: undefined },
     _inactive: null,
     _directInactive: false,
     _isMounted: true,
     _isDestroyed: false,
     _isBeingDestroyed: false,
     _events: {},
     _hasHookEvent: false,
     _vnode:
      VNode {
        tag: 'vue-component-8-Test',
        data: [Object],
        children: undefined,
        text: undefined,
        elm: [HTMLDivElement],
        ns: undefined,
        context: [Circular],
        fnContext: undefined,
        fnOptions: undefined,
        fnScopeId: undefined,
        key: undefined,
        componentOptions: [Object],
        componentInstance: [Circular],
        parent: undefined,
        raw: false,
        isStatic: false,
        isRootInsert: true,
        isComment: false,
        isCloned: false,
        isOnce: false,
        asyncFactory: undefined,
        asyncMeta: undefined,
        isAsyncPlaceholder: false },
     _staticTrees: null,
     '$vnode': undefined,
     '$slots': {},
     '$scopedSlots': {},
     _c: [Function],
     '$createElement': [Function],
     '$attrs': [Getter/Setter],
     '$listeners': [Getter/Setter],
     __emitted: {},
     __emittedByOrder: [],
     '$emit': [Function],
     _watchers: [ [Watcher] ],
     _data: {},
     _provided: undefined,
     '$el':
      HTMLDivElement { _prevClass: 'container py-5 bg-success', __vue__: [Circular] } },
  '$children':
   [ VueComponent {
       _uid: 5,
       _isVue: true,
       '$options': [Object],
       _renderProxy: [VueComponent],
       _self: [Circular],
       '$parent': [Circular],
       '$root': [VueComponent],
       '$children': [],
       '$refs': {},
       _watcher: [Watcher],
       _inactive: null,
       _directInactive: false,
       _isMounted: true,
       _isDestroyed: false,
       _isBeingDestroyed: false,
       _events: {},
       _hasHookEvent: false,
       _vnode: [VNode],
       _staticTrees: null,
       '$vnode': [VNode],
       '$slots': [Object],
       '$scopedSlots': {},
       _c: [Function],
       '$createElement': [Function],
       '$attrs': [Getter/Setter],
       '$listeners': [Getter/Setter],
       __emitted: {},
       __emittedByOrder: [],
       '$emit': [Function],
       _watchers: [Array],
       _data: {},
       '$el': [HTMLUnknownElement],
       '$_vueTestUtils_updateInSetWatcherSync': [Function],
       _update: [Function] } ],
  '$refs': {},
  _watcher:
   Watcher {
     vm: [Circular],
     sync: true,
     lazy: false,
     user: false,
     deep: false,
     cb: [Function: noop],
     id: 7,
     active: true,
     dirty: false,
     deps: [ [Dep], [Dep] ],
     newDeps: [],
     depIds: Set { 30, 31 },
     newDepIds: Set {},
     expression:
      'function () {\n      vm._update(vm._render(), hydrating);\n    }',
     getter: [Function: updateComponent],
     value: undefined },
  _inactive: null,
  _directInactive: false,
  _isMounted: true,
  _isDestroyed: false,
  _isBeingDestroyed: false,
  _events: {},
  _hasHookEvent: false,
  _vnode:
   VNode {
     tag: 'div',
     data: { staticClass: 'container py-5 bg-success' },
     children: [ [VNode] ],
     text: undefined,
     elm:
      HTMLDivElement {
        _prevClass: 'container py-5 bg-success',
        __vue__: [VueComponent] },
     ns: undefined,
     context: [Circular],
     fnContext: undefined,
     fnOptions: undefined,
     fnScopeId: undefined,
     key: undefined,
     componentOptions: undefined,
     componentInstance: undefined,
     parent:
      VNode {
        tag: 'vue-component-8-Test',
        data: [Object],
        children: undefined,
        text: undefined,
        elm: [HTMLDivElement],
        ns: undefined,
        context: [VueComponent],
        fnContext: undefined,
        fnOptions: undefined,
        fnScopeId: undefined,
        key: undefined,
        componentOptions: [Object],
        componentInstance: [Circular],
        parent: undefined,
        raw: false,
        isStatic: false,
        isRootInsert: true,
        isComment: false,
        isCloned: false,
        isOnce: false,
        asyncFactory: undefined,
        asyncMeta: undefined,
        isAsyncPlaceholder: false },
     raw: false,
     isStatic: false,
     isRootInsert: true,
     isComment: false,
     isCloned: false,
     isOnce: false,
     asyncFactory: undefined,
     asyncMeta: undefined,
     isAsyncPlaceholder: false },
  _staticTrees:
   [ VNode {
       tag: 'blockquote',
       data: [Object],
       children: [Array],
       text: undefined,
       elm: [HTMLQuoteElement],
       ns: undefined,
       context: [Circular],
       fnContext: undefined,
       fnOptions: undefined,
       fnScopeId: undefined,
       key: '__static__0',
       componentOptions: undefined,
       componentInstance: undefined,
       parent: undefined,
       raw: false,
       isStatic: true,
       isRootInsert: false,
       isComment: false,
       isCloned: false,
       isOnce: false,
       asyncFactory: undefined,
       asyncMeta: undefined,
       isAsyncPlaceholder: false } ],
  '$vnode':
   VNode {
     tag: 'vue-component-8-Test',
     data:
      { ref: 'vm',
        on: undefined,
        attrs: {},
        scopedSlots: {},
        hook: [Object],
        pendingInsert: null },
     children: undefined,
     text: undefined,
     elm:
      HTMLDivElement {
        _prevClass: 'container py-5 bg-success',
        __vue__: [VueComponent] },
     ns: undefined,
     context:
      VueComponent {
        _uid: 3,
        _isVue: true,
        '$options': [Object],
        _renderProxy: [VueComponent],
        _self: [Circular],
        '$parent': undefined,
        '$root': [Circular],
        '$children': [Array],
        '$refs': [Object],
        _watcher: [Watcher],
        _inactive: null,
        _directInactive: false,
        _isMounted: true,
        _isDestroyed: false,
        _isBeingDestroyed: false,
        _events: {},
        _hasHookEvent: false,
        _vnode: [Circular],
        _staticTrees: null,
        '$vnode': undefined,
        '$slots': {},
        '$scopedSlots': {},
        _c: [Function],
        '$createElement': [Function],
        '$attrs': [Getter/Setter],
        '$listeners': [Getter/Setter],
        __emitted: {},
        __emittedByOrder: [],
        '$emit': [Function],
        _watchers: [Array],
        _data: {},
        _provided: undefined,
        '$el': [HTMLDivElement] },
     fnContext: undefined,
     fnOptions: undefined,
     fnScopeId: undefined,
     key: undefined,
     componentOptions:
      { Ctor: [Function],
        propsData: {},
        listeners: undefined,
        tag: undefined,
        children: undefined },
     componentInstance: [Circular],
     parent: undefined,
     raw: false,
     isStatic: false,
     isRootInsert: true,
     isComment: false,
     isCloned: false,
     isOnce: false,
     asyncFactory: undefined,
     asyncMeta: undefined,
     isAsyncPlaceholder: false },
  '$slots': {},
  '$scopedSlots': {},
  _c: [Function],
  '$createElement': [Function],
  '$attrs': [Getter/Setter],
  '$listeners': [Getter/Setter],
  __emitted: {},
  __emittedByOrder: [],
  '$emit': [Function],
  _watchers:
   [ Watcher {
       vm: [Circular],
       deep: false,
       user: true,
       lazy: false,
       sync: true,
       cb: [Function: quantity],
       id: 6,
       active: true,
       dirty: false,
       deps: [Array],
       newDeps: [],
       depIds: [Set],
       newDepIds: Set {},
       expression: 'quantity',
       getter: [Function],
       value: 0 },
     Watcher {
       vm: [Circular],
       sync: true,
       lazy: false,
       user: false,
       deep: false,
       cb: [Function: noop],
       id: 7,
       active: true,
       dirty: false,
       deps: [Array],
       newDeps: [],
       depIds: [Set],
       newDepIds: Set {},
       expression:
        'function () {\n      vm._update(vm._render(), hydrating);\n    }',
       getter: [Function: updateComponent],
       value: undefined } ],
  _props: { slug: [Getter/Setter] },
  fetchResults: [Function: bound fetchResults],
  updateCount: [Function: bound updateCount],
  increment: [Function: bound increment],
  decrement: [Function: bound decrement],
  clear: [Function: bound clear],
  onKeydown: [Function: bound onKeydown],
  _data:
   { count: [Getter/Setter],
     quantity: [Getter/Setter],
     value: [Getter/Setter] },
  value: [Getter/Setter],
  quantity: [Getter/Setter],
  count: [Getter/Setter],
  '$el':
   HTMLDivElement {
     _prevClass: 'container py-5 bg-success',
     __vue__:
      VueComponent {
        _uid: 3,
        _isVue: true,
        '$options': [Object],
        _renderProxy: [VueComponent],
        _self: [Circular],
        '$parent': undefined,
        '$root': [Circular],
        '$children': [Array],
        '$refs': [Object],
        _watcher: [Watcher],
        _inactive: null,
        _directInactive: false,
        _isMounted: true,
        _isDestroyed: false,
        _isBeingDestroyed: false,
        _events: {},
        _hasHookEvent: false,
        _vnode: [VNode],
        _staticTrees: null,
        '$vnode': undefined,
        '$slots': {},
        '$scopedSlots': {},
        _c: [Function],
        '$createElement': [Function],
        '$attrs': [Getter/Setter],
        '$listeners': [Getter/Setter],
        __emitted: {},
        __emittedByOrder: [],
        '$emit': [Function],
        _watchers: [Array],
        _data: {},
        _provided: undefined,
        '$el': [Circular] } },
  '$_vueTestUtils_updateInSetWatcherSync': [Function],
  _update: [Function] }
